#!/usr/bin/env bash
# Setting up server to curl port 80 with no issues
apt-get update
apt-get -y install curl
apt-get intsall -y nginx 
rm -f /etc/nginx/sites-available/*
rm -f /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
