#!/usr/bin/env bash
# Manage process
# start: will start the process
# stop : will stop the process
# restrt: will stop and start the process

arg=$1

case "$arg" in
    start)
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -e /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
   restart)
	   if [ -e /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            #echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
	./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"

	;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
        ;;
esac
